name: Telegram Notification

on:
  pull_request:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>🚀 Pull Request Notification</b>
            <hr>
            <b>Repository:</b> ${{ github.repository }}<br>
            <b>PR Number:</b> #${{ github.event.pull_request.number }}<br>
            <b>Title:</b> ${{ github.event.pull_request.title }}<br>
            <b>Author:</b> ${{ github.event.pull_request.user.login }}<br>
            <b>Branch:</b> <code>${{ github.event.pull_request.head.ref }}</code> → <code>${{ github.event.pull_request.base.ref }}</code><br>
            <b>Status:</b> ${{ github.event.pull_request.state }}<br>
            <b>Created At:</b> ${{ github.event.pull_request.created_at }}<br>
            <b>Last Updated:</b> ${{ github.event.pull_request.updated_at }}<br>
            <b>Files Changed:</b> ${{ github.event.pull_request.changed_files }}<br>
            <b>Lines Added:</b> +${{ github.event.pull_request.additions }}<br>
            <b>Lines Removed:</b> -${{ github.event.pull_request.deletions }}<br>
            <b>Commits in PR:</b> ${{ github.event.pull_request.commits }}<br>
            <b>🔗 <a href="${{ github.event.pull_request.html_url }}">View PR</a></b>
